<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        view()->composer('*', function ($view) {
            $lang = request()->query('lang', session('lang', 'en'));
            if (!in_array($lang, ['en', 'hi', 'pb'])) {
                $lang = 'en';
            }
            session(['lang' => $lang]);

            $trans = self::getTranslationDictionary();
            $view->with('lang', $lang);
            $view->with('t', $trans[$lang]);
        });
    }

    /**
     * Centralized localization translation dictionary for English, Hindi, and Punjabi parity.
     */
    public static function getTranslationDictionary()
    {
        return [
            'hi' => [
                'latest_news' => 'ताजा खबरें',
                'epaper' => 'ई-पेपर',
                'video' => 'वीडियो',
                'settings' => 'सेटिंग्स',
                'subscribe' => 'सब्सक्राइब',
                'search' => 'खबर खोजें...',
                'home' => 'होम',
                'national' => 'देश',
                'state' => 'राज्य',
                'politics' => 'राजनीति',
                'sports' => 'खेल',
                'business' => 'बिजनेस',
                'technology' => 'टेक्नोलॉजी',
                'entertainment' => 'मनोरंजन',
                'lifestyle' => 'लाइफस्टाइल',
                'education' => 'एजुकेशन',
                'world' => 'दुनिया',
                'gallery' => 'फोटो गैलरी',
                'more' => 'और',
                'career' => 'करियर',
                'religion' => 'धर्म / धर्म-कर्म',
                'share_news' => 'अपनी खबर हमें भेजें',
                'readers_voice' => 'पंजाब की आवाज',
                'share_your_news' => 'Share Your News +',
                'trending' => 'ट्रेडिंग न्यूज़',
                'most_read' => 'सबसे ज्यादा पढ़ी गई',
                'video_news' => 'वीडियो समाचार',
                'newsletter' => 'ताजा खबरों के लिए न्यूज़लेटर सब्सक्राइब करें',
                'subscribe_btn' => 'सब्सक्राइब करें',
                'footer_tagline' => 'हमेशा आगे, हर पल की खबर',
                'dashboard' => 'डैशबोर्ड',
                'logout' => 'लॉगआउट',
                'login_register' => 'लॉगिन / रजिस्ट्रेशन',
                'live_tv' => 'लाइव टीवी',
                'app_download' => 'एप डाउनलोड',
                'menu_open' => 'मेन्यू खोलें',
                'breaking_news' => 'ब्रेकिंग न्यूज़',
                'category_feed' => 'श्रेणी फ़ीड',
                'back_to_home' => 'मुख्य पृष्ठ',
                'no_articles' => 'कोई लेख नहीं मिला',
                'no_articles_desc' => 'इस श्रेणी में अभी तक कोई समाचार लेख प्रकाशित नहीं हुआ है।',
                'english_news' => 'अंग्रेजी समाचार',
                'hindi_news' => 'हिंदी समाचार',
                'punjabi_news' => 'पंजाबी समाचार',
                'readers_corner' => 'रीडर्स कॉर्नर',
                'daily_updates' => 'दैनिक अपडेट',
                'read_now' => 'अभी पढ़ें',
                'share_updates' => 'अपनी खबर साझा करें',
                'submit_post' => 'पोस्ट भेजें',
                'view_all' => 'सभी देखें',
                'view_more' => 'और देखें',
                'instagram_title' => 'इंस्टाग्राम वीडियो & रील्स',
                'instagram_video' => 'इंस्टाग्राम वीडियो',
                'no_instagram' => 'अभी तक कोई इंस्टाग्राम वीडियो नहीं जोड़ा गया है।',
                'news_by_category' => 'खबरें श्रेणी अनुसार',
                'premium_title' => 'AAKASH NEWS 24 प्रीमियम',
                'premium_desc' => 'निष्पक्ष पत्रकारिता का समर्थन करें। आज ही सदस्यता लें।',
                'subscribe_now' => 'अभी सदस्यता लें',
                'success' => 'सफलता!',
                'ok' => 'ठीक है',
                'login_title' => 'लॉगिन करें',
                'name' => 'नाम',
                'enter_name' => 'अपना नाम लिखें',
                'email_address' => 'ईमेल पता',
                'enter_email' => 'अपना ईमेल लिखें',
                'password' => 'पासवर्ड',
                'enter_password' => 'पासवर्ड लिखें',
                'confirm_password' => 'पासवर्ड की पुष्टि करें',
                'retype_password' => 'पासवर्ड पुनः लिखें',
                'dont_have_account' => 'खाता नहीं है?',
                'register_now' => 'रजिस्टर करें',
                'explore' => 'एक्सप्लोर',
                'categories' => 'कैटेगरी',
                'help_support' => 'सहायता',
                'about_us' => 'हमारे बारे में',
                'contact_us' => 'संपर्क करें',
                'privacy_policy' => 'गोपनीयता नीति',
                'terms_conditions' => 'नियम & शर्तें',
                'download_mobile_app' => 'मोबाइल ऐप डाउनलोड करें',
                'all_rights_reserved' => 'सभी अधिकार सुरक्षित।',
                'close' => 'बंद करें',
                'prev_video' => 'पिछला वीडियो (Arrow Up)',
                'next_video' => 'अगला वीडियो (Arrow Down)',
                'share_facebook' => 'फेसबुक पर शेयर करें',
                'share_twitter' => 'ट्विटर पर शेयर करें',
                'copy_link' => 'लिंक कॉपी करें',
                'video_label' => 'वीडियो: ',
                'font_minus' => 'फ़ॉन्ट छोटा करें',
                'font_reset' => 'फ़ॉन्ट रीसेट करें',
                'font_plus' => 'फ़ॉन्ट बड़ा करें',
                'toggle_theme' => 'थीम बदलें',
                'short_video' => 'शॉर्ट वीडियो',
                'just_now' => 'अभी-अभी',
                'news' => 'न्यूज़',
                'rewind_5' => '5 सेकंड पीछे',
                'forward_5' => '5 सेकंड आगे',
                'pause' => 'पॉज़',
                'mute' => 'म्यूट',
                'read_news' => 'खबर पढ़ें',
                'link_copied' => 'लिंक कॉपी कर लिया गया है!',
                'meta_desc' => 'Aakash News 24 - Always Ahead। हिंदी न्यूज़ पोर्टल।',
                'meta_title' => 'हिंदी न्यूज़ पोर्टल',
                'admin_area' => 'एडमिन क्षेत्र',
                'search_here' => 'यहाँ खोजें...',
                'dark_mode' => '🌙 डार्क मोड',
                'super_admin' => 'सुपर एडमिन',
                'news_articles' => 'समाचार लेख',
                'advertisements' => 'विज्ञापन',
                'instagram_reels' => 'इंस्टाग्राम रील्स',
                'subscribers' => 'सब्सक्राइबर',
                'ai_moderation_status' => 'AI मॉडरेशन स्थिति',
                'ai_moderation_desc' => 'स्थिति: 100% सक्रिय। सभी पोस्ट स्वतः स्कैन और संसाधित।',
                'live_broadcast' => 'लाइव प्रसारण',
                'aakash_news' => 'आकाश न्यूज़ 24',
                'broadcast_desc' => 'हमेशा आगे। राष्ट्रीय और स्थानीय ब्रेकिंग न्यूज 24/7 का सीधा प्रसारण।',
                'view_live_tv' => 'लाइव टीवी देखें',
            ],
            'en' => [
                'latest_news' => 'Latest News',
                'epaper' => 'E-Paper',
                'video' => 'Videos',
                'settings' => 'Settings',
                'subscribe' => 'Subscribe',
                'search' => 'Search news...',
                'home' => 'Home',
                'national' => 'National',
                'state' => 'State',
                'politics' => 'Politics',
                'sports' => 'Sports',
                'business' => 'Business',
                'technology' => 'Technology',
                'entertainment' => 'Entertainment',
                'lifestyle' => 'Lifestyle',
                'education' => 'Education',
                'world' => 'World',
                'gallery' => 'Photo Gallery',
                'more' => 'More',
                'career' => 'Career',
                'religion' => 'Religion',
                'share_news' => 'Send us your news',
                'readers_voice' => 'Voice of Punjab',
                'share_your_news' => 'Share Your News +',
                'trending' => 'Trending News',
                'most_read' => 'Most Read Articles',
                'video_news' => 'Video News Desk',
                'newsletter' => 'Subscribe to Newsletter for Latest Updates',
                'subscribe_btn' => 'Subscribe Now',
                'footer_tagline' => 'Always ahead, news every second',
                'dashboard' => 'Dashboard',
                'logout' => 'Logout',
                'login_register' => 'Login / Register',
                'live_tv' => 'Live TV',
                'app_download' => 'App Download',
                'menu_open' => 'Open Menu',
                'breaking_news' => 'Breaking News',
                'category_feed' => 'Category Feed',
                'back_to_home' => 'Back to Home',
                'no_articles' => 'No Articles Found',
                'no_articles_desc' => 'No news articles have been published in this category yet.',
                'english_news' => 'ENGLISH NEWS',
                'hindi_news' => 'HINDI NEWS',
                'punjabi_news' => 'PUNJABI NEWS',
                'readers_corner' => 'READER\'S CORNER',
                'daily_updates' => 'Daily updates',
                'read_now' => 'Read Now',
                'share_updates' => 'Share your updates',
                'submit_post' => 'Submit Post',
                'view_all' => 'View All',
                'view_more' => 'View More',
                'instagram_title' => 'Instagram Videos & Reels',
                'instagram_video' => 'Instagram Video',
                'no_instagram' => 'No Instagram videos added yet.',
                'news_by_category' => 'News By Category',
                'premium_title' => 'AAKASH NEWS 24 Premium',
                'premium_desc' => 'Support independent journalism. Subscribe today.',
                'subscribe_now' => 'Subscribe Now',
                'success' => 'Success!',
                'ok' => 'OK',
                'login_title' => 'Login',
                'name' => 'Name',
                'enter_name' => 'Enter your name',
                'email_address' => 'Email Address',
                'enter_email' => 'Enter your email',
                'password' => 'Password',
                'enter_password' => 'Enter password',
                'confirm_password' => 'Confirm Password',
                'retype_password' => 'Re-type password',
                'dont_have_account' => 'Don\'t have an account?',
                'register_now' => 'Register Now',
                'explore' => 'Explore',
                'categories' => 'Categories',
                'help_support' => 'Help & Support',
                'about_us' => 'About Us',
                'contact_us' => 'Contact Us',
                'privacy_policy' => 'Privacy Policy',
                'terms_conditions' => 'Terms & Conditions',
                'download_mobile_app' => 'Download Mobile App',
                'all_rights_reserved' => 'All rights reserved.',
                'close' => 'Close',
                'prev_video' => 'Previous Video (Arrow Up)',
                'next_video' => 'Next Video (Arrow Down)',
                'share_facebook' => 'Share on Facebook',
                'share_twitter' => 'Share on Twitter',
                'copy_link' => 'Copy Link',
                'video_label' => 'Video: ',
                'font_minus' => 'Decrease Font Size',
                'font_reset' => 'Reset Font Size',
                'font_plus' => 'Increase Font Size',
                'toggle_theme' => 'Toggle Theme',
                'short_video' => 'Short Video',
                'just_now' => 'Just now',
                'news' => 'News',
                'rewind_5' => '5 seconds back',
                'forward_5' => '5 seconds forward',
                'pause' => 'Pause',
                'mute' => 'Mute',
                'read_news' => 'Read News',
                'link_copied' => 'Link copied to clipboard!',
                'meta_desc' => 'Aakash News 24 - Always Ahead. English News Portal.',
                'meta_title' => 'English News Portal',
                'admin_area' => 'Admin area',
                'search_here' => 'Search here...',
                'dark_mode' => '🌙 Dark Mode',
                'super_admin' => 'Super Admin',
                'news_articles' => 'News Articles',
                'advertisements' => 'Advertisements',
                'instagram_reels' => 'Instagram Reels',
                'subscribers' => 'Subscribers',
                'ai_moderation_status' => 'AI Moderation Status',
                'ai_moderation_desc' => 'Status: 100% Active. All posts automatically scanned and processed.',
                'live_broadcast' => 'LIVE BROADCAST',
                'aakash_news' => 'AAKASH NEWS',
                'broadcast_desc' => 'Always ahead. Live coverage of national and local breaking news 24/7.',
                'view_live_tv' => 'View Live TV',
            ],
            'pb' => [
                'latest_news' => 'ਤਾਜ਼ਾ ਖ਼ਬਰਾਂ',
                'epaper' => 'ਈ-ਪੇਪਰ',
                'video' => 'ਵੀਡੀਓ',
                'settings' => 'ਸੈਟਿੰਗਾਂ',
                'subscribe' => 'ਸਬਸਕ੍ਰਾਈਬ',
                'search' => 'ਖ਼ਬਰ ਲੱਭੋ...',
                'home' => 'ਹੋਮ',
                'national' => 'ਦੇਸ਼',
                'state' => 'ਰਾਜ',
                'politics' => 'ਰਾਜਨੀਤੀ',
                'sports' => 'ਖੇਡਾਂ',
                'business' => 'ਵਪਾਰ',
                'technology' => 'ਤਕਨਾਲੋਜੀ',
                'entertainment' => 'ਮਨੋਰੰਜਨ',
                'lifestyle' => 'ਜੀਵਨ ਸ਼ੈਲੀ',
                'education' => 'ਸਿੱਖਿਆ',
                'world' => 'ਦੁਨੀਆ',
                'gallery' => 'ਫੋਟੋ ਗੈਲਰੀ',
                'more' => 'ਹੋਰ',
                'career' => 'ਕਰੀਅਰ',
                'religion' => 'ਧਰਮ',
                'share_news' => 'ਆਪਣੀ ਖ਼ਬਰ ਸਾਨੂੰ ਭੇਜੋ',
                'readers_voice' => 'ਪੰਜਾਬ ਦੀ ਆਵਾਜ਼',
                'share_your_news' => 'ਖ਼ਬਰ ਸਾਂਝੀ ਕਰੋ +',
                'trending' => 'ਟ੍ਰੈਂਡਿੰਗ ਖ਼ਬਰਾਂ',
                'most_read' => 'ਸਭ ਤੋਂ ਵੱਧ ਪੜ੍ਹੀਆਂ ਗਈਆਂ',
                'video_news' => 'ਵੀਡੀਓ ਖ਼ਬਰਾਂ',
                'newsletter' => 'ਤਾਜ਼ਾ ਖ਼ਬਰਾਂ ਲਈ ਨਿਊਜ਼ਲੈਟਰ ਸਬਸਕ੍ਰਾਈਬ ਕਰੋ',
                'subscribe_btn' => 'ਹੁਣੇ ਸਬਸਕ੍ਰਾਈਬ ਕਰੋ',
                'footer_tagline' => 'ਹਮੇਸ਼ਾ ਅੱਗੇ, ਹਰ ਪਲ ਦੀ ਖ਼ਬਰ',
                'dashboard' => 'ਡੈਸ਼ਬੋਰਡ',
                'logout' => 'ਲੌਗਆਉਟ',
                'login_register' => 'ਲੌਗਇਨ / ਰਜਿਸਟ੍ਰੇਸ਼ਨ',
                'live_tv' => 'ਲਾਈਵ ਟੀਵੀ',
                'app_download' => 'ਐਪ ਡਾਊਨਲੋਡ',
                'menu_open' => 'ਮੇਨੂ ਖੋਲ੍ਹੋ',
                'breaking_news' => 'ਤਾਜ਼ਾ ਖ਼ਬਰਾਂ',
                'category_feed' => 'ਸ਼੍ਰੇਣੀ ਫੀਡ',
                'back_to_home' => 'ਮੁੱਖ ਪੰਨਾ',
                'no_articles' => 'ਕੋਈ ਲੇਖ ਨਹੀਂ ਮਿਲਿਆ',
                'no_articles_desc' => 'ਇਸ ਸ਼੍ਰੇਣੀ ਵਿੱਚ ਅਜੇ ਤੱਕ ਕੋਈ ਖ਼ਬਰ ਲੇਖ ਪ੍ਰਕਾਸ਼ਿਤ ਨਹੀਂ ਹੋਇਆ ਹੈ।',
                'english_news' => 'ਅੰਗਰੇਜ਼ੀ ਖ਼ਬਰਾਂ',
                'hindi_news' => 'ਹਿੰਦੀ ਖ਼ਬਰਾਂ',
                'punjabi_news' => 'ਪੰਜਾਬੀ ਖ਼ਬਰਾਂ',
                'readers_corner' => 'ਪਾਠਕ ਕੋਨਾ',
                'daily_updates' => 'ਰੋਜ਼ਾਨਾ ਅੱਪਡੇਟ',
                'read_now' => 'ਹੁਣੇ ਪੜ੍ਹੋ',
                'share_updates' => 'ਆਪਣੀ ਖ਼ਬਰ ਸਾਂਝੀ ਕਰੋ',
                'submit_post' => 'ਪੋਸਟ ਭੇਜੋ',
                'view_all' => 'ਸਾਰੇ ਦੇਖੋ',
                'view_more' => 'ਹੋਰ ਦੇਖੋ',
                'instagram_title' => 'ਇੰਸਟਾਗ੍ਰਾਮ ਵੀਡੀਓ ਅਤੇ ਰੀਲਾਂ',
                'instagram_video' => 'ਇੰਸਟਾਗ੍ਰਾਮ ਵੀਡੀਓ',
                'no_instagram' => 'ਅਜੇ ਤੱਕ ਕੋਈ ਇੰਸਟਾਗ੍ਰਾਮ ਵੀਡੀਓ ਨਹੀਂ ਜੋੜਿਆ ਗਿਆ।',
                'news_by_category' => 'ਸ਼੍ਰੇਣੀ ਅਨੁਸਾਰ ਖ਼ਬਰਾਂ',
                'premium_title' => 'ਆਕਾਸ਼ ਨਿਊਜ਼ 24 ਪ੍ਰੀਮੀਅਮ',
                'premium_desc' => 'ਨਿਰਪੱਖ ਪੱਤਰਕਾਰੀ ਦਾ ਸਮਰਥਨ ਕਰੋ। ਅੱਜ ਹੀ ਸਬਸਕ੍ਰਾਈਬ ਕਰੋ।',
                'subscribe_now' => 'ਹੁਣੇ ਸਬਸਕ੍ਰਾਈਬ ਕਰੋ',
                'success' => 'ਸਫਲਤਾ!',
                'ok' => 'ਠੀਕ ਹੈ',
                'login_title' => 'ਲੌਗਇਨ ਕਰੋ',
                'name' => 'ਨਾਮ',
                'enter_name' => 'ਆਪਣਾ ਨਾਮ ਲਿਖੋ',
                'email_address' => 'ਈਮੇਲ ਪਤਾ',
                'enter_email' => 'ਆਪਣਾ ਈਮੇਲ ਲਿਖੋ',
                'password' => 'ਪਾਸਵਰਡ',
                'enter_password' => 'ਪਾਸਵਰਡ ਲਿਖੋ',
                'confirm_password' => 'ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
                'retype_password' => 'ਪਾਸਵਰਡ ਦੁਬਾਰਾ ਲਿਖੋ',
                'dont_have_account' => 'ਖਾਤਾ ਨਹੀਂ ਹੈ?',
                'register_now' => 'ਰਜਿਸਟਰ ਕਰੋ',
                'explore' => 'ਐਕਸਪਲੋਰ ਕਰੋ',
                'categories' => 'ਸ਼੍ਰੇਣੀਆਂ',
                'help_support' => 'ਮਦਦ',
                'about_us' => 'ਸਾਡੇ ਬਾਰੇ',
                'contact_us' => 'ਸੰਪਰਕ ਕਰੋ',
                'privacy_policy' => 'ਪ੍ਰਾਈਵੇਸੀ ਪਾਲਿਸੀ',
                'terms_conditions' => 'ਨਿਯਮ ਅਤੇ ਸ਼ਰਤਾਂ',
                'download_mobile_app' => 'ਮੋਬਾਈਲ ਐਪ ਡਾਊਨਲੋਡ ਕਰੋ',
                'all_rights_reserved' => 'ਸਾਰੇ ਹੱਕ ਰਾਖਵੇਂ ਹਨ।',
                'close' => 'ਬੰਦ ਕਰੋ',
                'prev_video' => 'ਪਿਛਲਾ ਵੀਡੀਓ (Arrow Up)',
                'next_video' => 'ਅਗਲਾ ਵੀਡੀਓ (Arrow Down)',
                'share_facebook' => 'ਫੇਸਬੁੱਕ ਤੇ ਸ਼ੇਅਰ ਕਰੋ',
                'share_twitter' => 'ਟਵਿੱਟਰ ਤੇ ਸ਼ੇਅਰ ਕਰੋ',
                'copy_link' => 'ਲਿੰਕ ਕਾਪੀ ਕਰੋ',
                'video_label' => 'ਵੀਡੀਓ: ',
                'font_minus' => 'ਫੌਂਟ ਛੋਟਾ ਕਰੋ',
                'font_reset' => 'ਫੌਂਟ ਰੀਸੈਟ ਕਰੋ',
                'font_plus' => 'ਫੌਂਟ ਵੱਡਾ ਕਰੋ',
                'toggle_theme' => 'ਥੀਮ ਬਦਲੋ',
                'short_video' => 'ਸ਼ਾਰਟ ਵੀਡੀਓ',
                'just_now' => 'ਹੁਣੇ-ਹੁਣੇ',
                'news' => 'ਖ਼ਬਰਾਂ',
                'rewind_5' => '5 ਸਕਿੰਟ ਪਿੱਛੇ',
                'forward_5' => '5 ਸਕਿੰਟ ਅੱਗੇ',
                'pause' => 'ਪੌਜ਼',
                'mute' => 'ਮਿਊਟ',
                'read_news' => 'ਖ਼ਬਰ ਪੜ੍ਹੋ',
                'link_copied' => 'ਲਿੰਕ ਕਾਪੀ ਹੋ ਗਿਆ!',
                'meta_desc' => 'ਆਕਾਸ਼ ਨਿਊਜ਼ 24 - ਹਮੇਸ਼ਾ ਅੱਗੇ. ਪੰਜਾਬੀ ਖ਼ਬਰਾਂ।',
                'meta_title' => 'ਪੰਜਾਬੀ ਖ਼ਬਰ ਪੋਰਟਲ',
                'admin_area' => 'ਐਡਮਿਨ ਖੇਤਰ',
                'search_here' => 'ਇੱਥੇ ਖੋਜੋ...',
                'dark_mode' => '🌙 ਡਾਰਕ ਮੋਡ',
                'super_admin' => 'ਸੁਪਰ ਐਡਮਿਨ',
                'news_articles' => 'ਖ਼ਬਰਾਂ ਦੇ ਲੇਖ',
                'advertisements' => 'ਇਸ਼ਤਿਹਾਰ',
                'instagram_reels' => 'ਇੰਸਟਾਗ੍ਰਾਮ ਰੀਲਾਂ',
                'subscribers' => 'ਸਬਸਕ੍ਰਾਈਬਰਸ',
                'ai_moderation_status' => 'AI ਮਾਡਰੇਸ਼ਨ ਸਥਿਤੀ',
                'ai_moderation_desc' => 'ਸਥਿਤੀ: 100% ਸਰਗਰਮ। ਸਾਰੀਆਂ ਪੋਸਟਾਂ ਆਪਣੇ ਆਪ ਸਕੈਨ ਅਤੇ ਪ੍ਰੋਸੈਸ ਹੁੰਦੀਆਂ ਹਨ।',
                'live_broadcast' => 'ਲਾਈਵ ਪ੍ਰਸਾਰਣ',
                'aakash_news' => 'ਆਕਾਸ਼ ਨਿਊਜ਼ 24',
                'broadcast_desc' => 'ਹਮੇਸ਼ਾ ਅੱਗੇ। ਰਾਸ਼ਟਰੀ ਅਤੇ ਸਥਾਨਕ ਤਾਜ਼ਾ ਖ਼ਬਰਾਂ ਦਾ 24/7 ਲਾਈਵ ਪ੍ਰਸਾਰਣ।',
                'view_live_tv' => 'ਲਾਈਵ ਟੀਵੀ ਦੇਖੋ',
            ]
        ];
    }
}
